services:
  db :
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: mariadb123
      MARIADB_ROOT_PASSWORD: mariadbroot123
      MARIADB_DATABASE: backlogcleardb
    volumes:
      - "./database/mariadb-data/:/var/lib/mysql/"
    ports:
      - 3306:3306