//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacklogClear.Exception.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BacklogClear.Exception.Resources.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        public static string TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);
            }
        }
        
        public static string PLATFORM_REQUIRED {
            get {
                return ResourceManager.GetString("PLATFORM_REQUIRED", resourceCulture);
            }
        }
        
        public static string GENRE_REQUIRED {
            get {
                return ResourceManager.GetString("GENRE_REQUIRED", resourceCulture);
            }
        }
        
        public static string RELEASE_DATE_MUST_BE_IN_PAST {
            get {
                return ResourceManager.GetString("RELEASE_DATE_MUST_BE_IN_PAST", resourceCulture);
            }
        }
        
        public static string STATUS_INVALID {
            get {
                return ResourceManager.GetString("STATUS_INVALID", resourceCulture);
            }
        }
        
        public static string GAME_NOT_FOUND {
            get {
                return ResourceManager.GetString("GAME_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string START_DATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("START_DATE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        public static string END_DATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("END_DATE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        public static string START_DATE_MUST_BE_IN_PAST {
            get {
                return ResourceManager.GetString("START_DATE_MUST_BE_IN_PAST", resourceCulture);
            }
        }
        
        public static string END_DATE_MUST_BE_IN_PAST {
            get {
                return ResourceManager.GetString("END_DATE_MUST_BE_IN_PAST", resourceCulture);
            }
        }
    }
}
